export { default as VetraLogo } from './vetra-logo.svg'
export { default as SkyIsotype } from './sky-isotype.svg'
export { default as SkyLogotype } from './sky-logotype.svg'
export { default as KebabMenu } from './kebab-menu.svg'
export { default as PowerhouseLogo } from './powerhouse.svg'
