storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd

packages:
  '@*/*':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

max_body_size: 100mb
